const uniqueProducts = [
  // LIPS - 5 Products
  {
    id: 1,
    name: "Velvet Matte Lipstick",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "A luxurious matte lipstick that delivers intense color payoff with a velvety smooth finish. Long-lasting formula keeps lips hydrated and comfortable all day.",
    shades: ["Ruby Red", "Deep Maroon", "Rose Petal", "Nude Blush"],
    colors: ["#8B0000", "#5D1A1A", "#E8B4B8", "#D4A5A5"],
  },
  {
    id: 2,
    name: "High Shine Lip Gloss",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "A non-sticky lip gloss that delivers brilliant shine and subtle color. Enriched with vitamin E and jojoba oil for soft, supple lips.",
    shades: ["Crystal Clear", "Pink Shimmer", "Berry Burst", "Nude Glow"],
    colors: ["#F8F8F8", "#FFB6C1", "#8B0A50", "#D4A5A5"],
  },
  {
    id: 3,
    name: "Liquid Lip Stain",
    category: "Lips",
    image: "/images/products/lip-stain.jpg",
    description: "Ultra-pigmented liquid lip stain with long-lasting color that doesn't feather or bleed. Lightweight formula provides intense color in one swipe.",
    shades: ["Berry Wine", "Brick Red", "Mauve Dream", "Crimson Kiss"],
    colors: ["#6B1B47", "#A63D2A", "#9B7BA8", "#C41E3A"],
  },
  {
    id: 4,
    name: "Professional Lip Liner",
    category: "Lips",
    image: "/images/products/lip-liner.jpg",
    description: "Precision lip liner with a fine tip for perfect definition. Creamy formula glides smoothly without tugging. Available in versatile shades.",
    shades: ["Nude", "Rose", "Brick", "Berry"],
    colors: ["#C9A99A", "#D4869A", "#8B4513", "#5D3A5D"],
  },
  {
    id: 5,
    name: "Luxe Lip Balm SPF 30",
    category: "Lips",
    image: "/images/products/lip-balm.jpg",
    description: "Nourishing lip balm with SPF 30 protection and vitamin E. Hydrating formula prevents dryness while providing a subtle color tint.",
    shades: ["Clear", "Soft Pink", "Coral", "Berry"],
    colors: ["#FFEEDD", "#FFB6D9", "#FF9966", "#CC6699"],
  },

  // EYES - 5 Products
  {
    id: 6,
    name: "Sultry Eyes Palette",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "A stunning eyeshadow palette featuring 12 richly pigmented shades. From soft mattes to brilliant shimmers, create endless looks from day to night.",
    shades: ["Warm Neutrals", "Deep Burgundy", "Rose Gold", "Smoky Black"],
    colors: ["#C4A77D", "#722F37", "#B76E79", "#2C2C2C"],
  },
  {
    id: 7,
    name: "Volumizing Mascara",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "An intensely volumizing mascara that creates dramatic, full lashes without clumping. Smudge-proof and long-wearing formula for all-day impact.",
    shades: ["Jet Black", "Deep Brown"],
    colors: ["#0A0A0A", "#3D2B1F"],
  },
  {
    id: 8,
    name: "Liquid Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Precision liquid eyeliner with a brush tip for sharp, defined lines. Waterproof formula stays put for 24 hours without budging.",
    shades: ["Jet Black", "Dark Brown", "Deep Navy"],
    colors: ["#000000", "#3D2B1F", "#191970"],
  },
  {
    id: 9,
    name: "Eyebrow Pencil",
    category: "Eyes",
    image: "/images/products/eyebrow-pencil.jpg",
    description: "Ultra-fine eyebrow pencil with spoolie brush. Creates natural-looking brows with precision control and long-wearing formula.",
    shades: ["Blonde", "Brunette", "Black", "Auburn"],
    colors: ["#B8860B", "#8B4513", "#000000", "#A0522D"],
  },
  {
    id: 10,
    name: "Cream Eyeshadow Stick",
    category: "Eyes",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Easy-to-apply cream eyeshadow stick that glides on smoothly. Available in matte, shimmer, and metallic finishes.",
    shades: ["Champagne", "Rose Gold", "Chocolate", "Navy"],
    colors: ["#FDD5B1", "#E8B4A8", "#8B4513", "#191970"],
  },

  // FACE - 5 Products
  {
    id: 11,
    name: "Flawless Skin Foundation",
    category: "Face",
    image: "/images/products/foundation.jpg",
    description: "A buildable, medium-to-full coverage foundation that blurs imperfections and creates a naturally radiant finish. Infused with skincare ingredients for all-day comfort.",
    shades: ["Porcelain", "Fair", "Medium", "Tan", "Deep"],
    colors: ["#F5E6D3", "#E8D4B8", "#D4A574", "#A67B5B", "#6B4423"],
  },
  {
    id: 12,
    name: "Rose Bloom Blush",
    category: "Face",
    image: "/images/products/blush.jpg",
    description: "A silky pressed blush that delivers a natural flush of color. Buildable formula allows for subtle to dramatic looks. Infused with rose extracts for skin-loving benefits.",
    shades: ["Soft Pink", "Coral Rose", "Berry Flush", "Peach Glow"],
    colors: ["#FFB6C1", "#E57373", "#A94064", "#FFCBA4"],
  },
  {
    id: 13,
    name: "Illuminating Highlighter",
    category: "Face",
    image: "/images/products/highlighter.jpg",
    description: "Luminous highlighter powder that catches light beautifully. Creates a natural-looking glow without glitter or sparkle.",
    shades: ["Champagne", "Rose Gold", "Gold", "Moonlight"],
    colors: ["#F7E98E", "#E8B4A8", "#FFD700", "#E5E4E2"],
  },
  {
    id: 14,
    name: "Luminous Primer",
    category: "Face",
    image: "/images/products/primer.jpg",
    description: "Silky primer that smooths skin and extends makeup wear. Creates a luminous base perfect for all skin types.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 15,
    name: "Cream Contour Palette",
    category: "Face",
    image: "/images/products/contour.jpg",
    description: "Versatile cream contour palette with sculpting shades. Blendable formula for professional contouring results.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#D4A574", "#8B6914", "#654321"],
  },

  // SKINCARE - 5 Products
  {
    id: 16,
    name: "Gentle Facial Cleanser",
    category: "Skincare",
    image: "/images/products/face-cleanser.jpg",
    description: "Creamy cleanser formulated for all skin types. Removes makeup and impurities while maintaining skin's natural moisture balance.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 17,
    name: "Hydrating Toner",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Lightweight hydrating toner that balances pH. Contains hyaluronic acid for deep moisture penetration.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 18,
    name: "Vitamin C Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Brightening vitamin C serum for radiant skin. Antioxidant formula reduces dark spots and improves skin texture.",
    shades: ["Golden"],
    colors: ["#FFD700"],
  },
  {
    id: 19,
    name: "Retinol Night Cream",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Nourishing night cream with retinol for cell renewal. Reduces fine lines and improves skin elasticity while you sleep.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 20,
    name: "Hyaluronic Acid Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Hydrating serum with hyaluronic acid molecules. Plumps skin and maintains moisture for 24 hours.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },

  // EYE SHADOW - 2 Products
  {
    id: 21,
    name: "Prismatic Eyeshadow Palette",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Multidimensional eyeshadow palette with iridescent shades. Creates holographic, color-shifting eye looks.",
    shades: ["Hologram", "Aurora", "Opal", "Prism"],
    colors: ["#F0F8FF", "#E0FFFF", "#F5F5DC", "#FFE4E1"],
  },
  {
    id: 22,
    name: "Velvet Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Smooth velvet eyeshadow with buttery texture. Blends effortlessly for seamless color application.",
    shades: ["Plum", "Rose", "Taupe", "Bronze"],
    colors: ["#4B0082", "#FF1493", "#A9927D", "#CD7F32"],
  },

  // HIGHLIGHTER - 2 Products
  {
    id: 23,
    name: "Luminous Glow Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Luminous highlighter with subtle shimmer for natural-looking glow. Flatters all skin tones beautifully.",
    shades: ["Champagne", "Rose Gold", "Gold"],
    colors: ["#F7E98E", "#E8B4A8", "#FFD700"],
  },
  {
    id: 24,
    name: "Liquid Glow Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Liquid highlighter that can be mixed with foundation for all-over glow. Creates dewy, radiant finish.",
    shades: ["Luminous", "Rosy", "Golden"],
    colors: ["#FFE4B5", "#E8B4A8", "#FFD700"],
  },

  // PRIMER - 2 Products
  {
    id: 25,
    name: "Luminous Face Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Silky primer with light-reflecting particles for luminous finish. Creates smooth base for makeup application.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 26,
    name: "Pore-Minimizing Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Mattifying primer that minimizes pore appearance. Creates poreless-looking base for makeup.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
]

export default uniqueProducts
