import { uploadProductsFromLocal } from "@/app/admin/utils";

const products = [
  // LIPS - 25 Products
  {
    id: 1,
    name: "Velvet Matte Lipstick",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "A luxurious matte lipstick that delivers intense color payoff with a velvety smooth finish. Long-lasting formula keeps lips hydrated and comfortable all day.",
    shades: ["Ruby Red", "Deep Maroon", "Rose Petal", "Nude Blush"],
    colors: ["#8B0000", "#5D1A1A", "#E8B4B8", "#D4A5A5"],
  },
  {
    id: 2,
    name: "High Shine Lip Gloss",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "A non-sticky lip gloss that delivers brilliant shine and subtle color. Enriched with vitamin E and jojoba oil for soft, supple lips.",
    shades: ["Crystal Clear", "Pink Shimmer", "Berry Burst", "Nude Glow"],
    colors: ["#F8F8F8", "#FFB6C1", "#8B0A50", "#D4A5A5"],
  },
  {
    id: 3,
    name: "Liquid Lip Stain",
    category: "Lips",
    image: "/images/products/lip-stain.jpg",
    description: "Ultra-pigmented liquid lip stain with long-lasting color that doesn't feather or bleed. Lightweight formula provides intense color in one swipe.",
    shades: ["Berry Wine", "Brick Red", "Mauve Dream", "Crimson Kiss"],
    colors: ["#6B1B47", "#A63D2A", "#9B7BA8", "#C41E3A"],
  },
  {
    id: 4,
    name: "Professional Lip Liner",
    category: "Lips",
    image: "/images/products/lip-liner.jpg",
    description: "Precision lip liner with a fine tip for perfect definition. Creamy formula glides smoothly without tugging. Available in versatile shades.",
    shades: ["Nude", "Rose", "Brick", "Berry"],
    colors: ["#C9A99A", "#D4869A", "#8B4513", "#5D3A5D"],
  },
  {
    id: 5,
    name: "Luxe Lip Balm SPF 30",
    category: "Lips",
    image: "/images/products/lip-balm.jpg",
    description: "Nourishing lip balm with SPF 30 protection and vitamin E. Hydrating formula prevents dryness while providing a subtle color tint.",
    shades: ["Clear", "Soft Pink", "Coral", "Berry"],
    colors: ["#FFEEDD", "#FFB6D9", "#FF9966", "#CC6699"],
  },
  {
    id: 6,
    name: "Satin Finish Lipstick",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "Creamy satin finish lipstick with moisturizing properties. Delivers buildable color from sheer to full coverage with a smooth, elegant finish.",
    shades: ["Peach", "Mauve", "Coral Pink", "Red Carpet"],
    colors: ["#FFAA88", "#C48080", "#FF7F7F", "#CC0000"],
  },
  {
    id: 7,
    name: "Bold Statement Lipstick",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "High-impact lipstick for bold, fearless looks. Long-wearing formula resists transfer while maintaining rich, vibrant color throughout the day.",
    shades: ["Scarlet", "Plum", "Burgundy", "Nude"],
    colors: ["#FF2400", "#880088", "#441111", "#DAA59C"],
  },
  {
    id: 8,
    name: "Glossy Lip Tint",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "Water-based lip tint with buildable color and glossy finish. Lightweight formula sits comfortably on lips all day without drying.",
    shades: ["Rose", "Plum", "Berry", "Coral"],
    colors: ["#FF9DBB", "#BB88DD", "#DD6688", "#FF8866"],
  },
  {
    id: 9,
    name: "Ultra Matte Lip Paint",
    category: "Lips",
    image: "/images/products/lip-stain.jpg",
    description: "Powdery matte lip paint with ultra-long wear. Lightweight and comfortable, this formula dries down to a stunning matte finish.",
    shades: ["Terracotta", "Dusty Rose", "Oxblood", "Mocha"],
    colors: ["#CD5C5C", "#DDA0AC", "#5D0000", "#8B6B47"],
  },
  {
    id: 10,
    name: "Shimmer Lip Dust",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "Lightweight shimmer dust that adds sparkle to lips. Can be worn alone or layered over lipstick for a dazzling, dimensional effect.",
    shades: ["Gold", "Rose Gold", "Silver", "Bronze"],
    colors: ["#FFD700", "#E8B4A8", "#C0C0C0", "#CD7F32"],
  },
  {
    id: 11,
    name: "Velvet Lip Cream",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "Soft velvet texture with moisturizing ingredients. Provides comfortable wear without flaking or drying lips throughout the day.",
    shades: ["Dusty Mauve", "Caramel", "Brick Red", "Deep Plum"],
    colors: ["#D8A0A0", "#C8975C", "#A84C3A", "#663333"],
  },
  {
    id: 12,
    name: "Precision Lip Gloss",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "Precision-tip gloss bottle ensures perfect application without mess. Sticky-free formula with plumping effect and rich, lustrous shine.",
    shades: ["Pink", "Red", "Nude", "Berry"],
    colors: ["#FFB6C1", "#FF0000", "#DAA59C", "#8B4789"],
  },
  {
    id: 13,
    name: "Color-Changing Lip Balm",
    category: "Lips",
    image: "/images/products/lip-balm.jpg",
    description: "Magical color-changing formula that adapts to your unique pH level. Nourishing balm that transitions from clear to a personalized shade.",
    shades: ["Universal"],
    colors: ["#FFE4E1"],
  },
  {
    id: 14,
    name: "Creamy Lip Pencil",
    category: "Lips",
    image: "/images/products/lip-liner.jpg",
    description: "Smooth, creamy pencil formula that doubles as both liner and lipstick. Easy to blend and layer for customizable color intensity.",
    shades: ["Peachy Nude", "Berry", "Mauve", "Coral"],
    colors: ["#F4A9A0", "#AA5C7A", "#B085A0", "#FF8040"],
  },
  {
    id: 15,
    name: "Metallic Liquid Lipstick",
    category: "Lips",
    image: "/images/products/lip-stain.jpg",
    description: "Liquid lipstick with metallic finish for a bold, eye-catching look. Long-wearing formula that stays put through eating and drinking.",
    shades: ["Copper", "Bronze", "Rose Gold", "Champagne"],
    colors: ["#B87333", "#AA5500", "#C5A572", "#F7E98E"],
  },
  {
    id: 16,
    name: "Hydrating Lip Essence",
    category: "Lips",
    image: "/images/products/lip-balm.jpg",
    description: "Lightweight essence that hydrates and plumps lips. Contains honey and plant extracts for soft, supple lips all day.",
    shades: ["Clear"],
    colors: ["#F5F5DC"],
  },
  {
    id: 17,
    name: "Retro Matte Lipstick",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "Classic matte lipstick with vintage-inspired color palette. Rich, opaque coverage with a drying matte finish.",
    shades: ["Brick", "Burgundy", "Scarlet", "Nude"],
    colors: ["#8B4513", "#441111", "#DC143C", "#C9A99A"],
  },
  {
    id: 18,
    name: "Gel-Based Lip Tint",
    category: "Lips",
    image: "/images/products/lip-stain.jpg",
    description: "Gel-based tint that provides natural, buildable color. Comfortable formula that layers beautifully with other lip products.",
    shades: ["Rose", "Peach", "Plum", "Berry"],
    colors: ["#FF69B4", "#FFCC99", "#DDA0DD", "#FF1493"],
  },
  {
    id: 19,
    name: "Soft Satin Tint",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "Soft satin finish tint with moisturizing formula. Provides subtle color with a comfortable, non-sticky feel.",
    shades: ["Blush", "Rose", "Coral", "Nude"],
    colors: ["#FFB6C1", "#FFB7C5", "#FF9966", "#E8B4A8"],
  },
  {
    id: 20,
    name: "Plumping Lip Serum",
    category: "Lips",
    image: "/images/products/lip-balm.jpg",
    description: "Peptide-enriched serum that gently plumps lips. Moisturizing formula enhances natural lip fullness over time.",
    shades: ["Clear"],
    colors: ["#FFE4E1"],
  },
  {
    id: 21,
    name: "Dual-Ended Lip Stick",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "Double-sided lipstick with complementary shades for creating gradient lips. Perfect for mixing and matching colors.",
    shades: ["Rose-Nude", "Berry-Pink", "Coral-Peach"],
    colors: ["#FF69B4", "#C9A99A", "#FF8040"],
  },
  {
    id: 22,
    name: "Mirror Gloss Collection",
    category: "Lips",
    image: "/images/products/lipgloss.jpg",
    description: "Mirror-finish gloss that reflects light for ultimate shine. Non-tacky formula provides gorgeous radiance.",
    shades: ["Diamond", "Pearl", "Gold", "Platinum"],
    colors: ["#E8E8E8", "#F0F8FF", "#FFD700", "#E5E4E2"],
  },
  {
    id: 23,
    name: "Bold Ombre Lip Set",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "Set of three coordinating shades for creating perfect ombre lips. Buildable formula allows custom blending.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#FFB6C1", "#FF69B4", "#8B0050"],
  },
  {
    id: 24,
    name: "Luxury Lip Butter",
    category: "Lips",
    image: "/images/products/lip-balm.jpg",
    description: "Rich, buttery formula with shea butter and argan oil. Nourishes while providing subtle color and shine.",
    shades: ["Natural", "Peachy", "Berry", "Nude"],
    colors: ["#FFF0F5", "#FFAA88", "#8B4789", "#C9A99A"],
  },
  {
    id: 25,
    name: "Flash Lipstick Palette",
    category: "Lips",
    image: "/images/products/matte-lipstick.jpg",
    description: "Compact palette with 4 essential shades. Perfect for touch-ups on the go with mirror and brush included.",
    shades: ["Red", "Nude", "Berry", "Coral"],
    colors: ["#FF0000", "#DAA59C", "#8B4789", "#FF7F50"],
  },

  // EYES - 25 Products
  {
    id: 26,
    name: "Sultry Eyes Palette",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "A stunning eyeshadow palette featuring 12 richly pigmented shades. From soft mattes to brilliant shimmers, create endless looks from day to night.",
    shades: ["Warm Neutrals", "Deep Burgundy", "Rose Gold", "Smoky Black"],
    colors: ["#C4A77D", "#722F37", "#B76E79", "#2C2C2C"],
  },
  {
    id: 27,
    name: "Volumizing Mascara",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "An intensely volumizing mascara that creates dramatic, full lashes without clumping. Smudge-proof and long-wearing formula for all-day impact.",
    shades: ["Jet Black", "Deep Brown"],
    colors: ["#0A0A0A", "#3D2B1F"],
  },
  {
    id: 28,
    name: "Liquid Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Precision liquid eyeliner with a brush tip for sharp, defined lines. Waterproof formula stays put for 24 hours without budging.",
    shades: ["Jet Black", "Dark Brown", "Deep Navy"],
    colors: ["#000000", "#3D2B1F", "#191970"],
  },
  {
    id: 29,
    name: "Eyebrow Pencil",
    category: "Eyes",
    image: "/images/products/eyebrow-pencil.jpg",
    description: "Ultra-fine eyebrow pencil with spoolie brush. Creates natural-looking brows with precision control and long-wearing formula.",
    shades: ["Blonde", "Brunette", "Black", "Auburn"],
    colors: ["#B8860B", "#8B4513", "#000000", "#A0522D"],
  },
  {
    id: 30,
    name: "Cream Eyeshadow Stick",
    category: "Eyes",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Easy-to-apply cream eyeshadow stick that glides on smoothly. Available in matte, shimmer, and metallic finishes.",
    shades: ["Champagne", "Rose Gold", "Chocolate", "Navy"],
    colors: ["#FDD5B1", "#E8B4A8", "#8B4513", "#191970"],
  },
  {
    id: 31,
    name: "Waterproof Mascara",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "Waterproof mascara that lasts through rain, sweat, and swimming. Tubing formula removes easily with warm water.",
    shades: ["Black", "Brown", "Burgundy"],
    colors: ["#000000", "#8B4513", "#800020"],
  },
  {
    id: 32,
    name: "Eyeshadow Palette Pro",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Professional eyeshadow palette with 16 versatile shades. Mix of mattes, shimmers, and metallics for any look.",
    shades: ["Nude", "Bronze", "Plum", "Gold"],
    colors: ["#DAA59C", "#CD7F32", "#DDA0DD", "#FFD700"],
  },
  {
    id: 33,
    name: "Gel Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Smooth gel eyeliner in a pot with applicator brush. Highly pigmented and smudge-proof for 24-hour wear.",
    shades: ["Black", "Charcoal", "Brown"],
    colors: ["#000000", "#414141", "#654321"],
  },
  {
    id: 34,
    name: "Lengthening Mascara",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "Lengthening mascara with a tapered wand. Separates and defines each lash while providing length.",
    shades: ["Black", "Dark Brown"],
    colors: ["#000000", "#3D2B1F"],
  },
  {
    id: 35,
    name: "Brow Pomade",
    category: "Eyes",
    image: "/images/products/brow-gel.jpg",
    description: "Creamy brow pomade with precision application. Holds brows in place all day with natural, dimensional finish.",
    shades: ["Ash Blonde", "Medium Brown", "Ebony"],
    colors: ["#C0C0C0", "#8B6914", "#000000"],
  },
  {
    id: 36,
    name: "Eyeshadow Duet",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Two complementary eyeshadow shades in a compact. Perfect for creating quick, cohesive eye looks.",
    shades: ["Light + Dark", "Shimmer + Matte"],
    colors: ["#F5E6D3", "#8B4513", "#B76E79"],
  },
  {
    id: 37,
    name: "Pencil Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Soft pencil eyeliner for easy blending. Works as both liner and eyeshadow with creamy formula.",
    shades: ["Black", "Brown", "Navy", "Plum"],
    colors: ["#000000", "#8B4513", "#191970", "#4B0082"],
  },
  {
    id: 38,
    name: "Lash Serum",
    category: "Eyes",
    image: "/images/products/lash-serum.jpg",
    description: "Nourishing lash serum with peptides and vitamins. Strengthens lashes and promotes natural growth over time.",
    shades: ["Clear"],
    colors: ["#FFFFFF"],
  },
  {
    id: 39,
    name: "Curl & Define Mascara",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "Curling mascara with shaped brush to curl and define. Lightweight formula holds curl without clumping.",
    shades: ["Black", "Brown"],
    colors: ["#000000", "#8B4513"],
  },
  {
    id: 40,
    name: "Brow Tint",
    category: "Eyes",
    image: "/images/products/eyebrow-pencil.jpg",
    description: "Staining brow tint for natural, long-lasting color. Semi-permanent formula lasts up to 6 weeks.",
    shades: ["Light Ash", "Medium Brown", "Dark Ash"],
    colors: ["#A9A9A9", "#8B6914", "#696969"],
  },
  {
    id: 41,
    name: "Eyeshadow Brush Set",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Professional set of eyeshadow brushes. Includes blending, definer, and shader brushes for flawless application.",
    shades: ["Natural Hair"],
    colors: ["#FFC0CB"],
  },
  {
    id: 42,
    name: "Kajal Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Creamy kajal liner for lining and smudging. Waterproof formula works on waterline and lash line.",
    shades: ["Black", "Brown", "Navy"],
    colors: ["#000000", "#8B4513", "#191970"],
  },
  {
    id: 43,
    name: "Eyeshadow Pigment",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Loose eyeshadow pigment in vibrant colors. Mix with liquid for gel eyeliner or use dry for intensity.",
    shades: ["Emerald", "Sapphire", "Ruby"],
    colors: ["#50C878", "#0F52BA", "#E0115F"],
  },
  {
    id: 44,
    name: "Lash Primer",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "Lash primer that conditions while boosting mascara performance. Creates fuller, thicker lashes with enhanced color.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 45,
    name: "Gel Brow Set",
    category: "Eyes",
    image: "/images/products/brow-gel.jpg",
    description: "Clear gel to set and shape brows. Long-holding formula keeps brows in place without frizz.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 46,
    name: "Metallic Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Metallic liquid eyeliner for glamorous, statement looks. Highly pigmented with shimmer finish.",
    shades: ["Gold", "Silver", "Rose Gold"],
    colors: ["#FFD700", "#C0C0C0", "#E8B4A8"],
  },
  {
    id: 47,
    name: "Eyebrow Stencil Set",
    category: "Eyes",
    image: "/images/products/eyebrow-pencil.jpg",
    description: "Reusable stencil set for perfect eyebrow shape. Works with pencil or powder for precise application.",
    shades: ["Universal"],
    colors: ["#C0C0C0"],
  },
  {
    id: 48,
    name: "Brown Mascara",
    category: "Eyes",
    image: "/images/products/mascara.jpg",
    description: "Warm brown mascara for a softer look. Perfect for fair complexions and creates a natural-looking enhancement.",
    shades: ["Chestnut", "Auburn"],
    colors: ["#8B4513", "#A0522D"],
  },
  {
    id: 49,
    name: "Eyeshadow Quad",
    category: "Eyes",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Compact four-shade eyeshadow palette. Mix of complementary colors for everyday and evening looks.",
    shades: ["Matte Nude", "Shimmer Taupe", "Pearl", "Deep Brown"],
    colors: ["#F5E6D3", "#A9927D", "#F0F8FF", "#8B4513"],
  },
  {
    id: 50,
    name: "Retractable Eyeliner",
    category: "Eyes",
    image: "/images/products/liquid-eyeliner.jpg",
    description: "Retractable pencil eyeliner with self-sharpening feature. Creamy formula glides smoothly for precise application.",
    shades: ["Black", "Brown", "Deep Navy"],
    colors: ["#000000", "#8B4513", "#191970"],
  },

  // FACE - 25 Products
  {
    id: 51,
    name: "Flawless Skin Foundation",
    category: "Face",
    image: "/images/products/foundation.jpg",
    description: "A buildable, medium-to-full coverage foundation that blurs imperfections and creates a naturally radiant finish. Infused with skincare ingredients for all-day comfort.",
    shades: ["Porcelain", "Fair", "Medium", "Tan", "Deep"],
    colors: ["#F5E6D3", "#E8D4B8", "#D4A574", "#A67B5B", "#6B4423"],
  },
  {
    id: 52,
    name: "Rose Bloom Blush",
    category: "Face",
    image: "/images/products/blush.jpg",
    description: "A silky pressed blush that delivers a natural flush of color. Buildable formula allows for subtle to dramatic looks. Infused with rose extracts for skin-loving benefits.",
    shades: ["Soft Pink", "Coral Rose", "Berry Flush", "Peach Glow"],
    colors: ["#FFB6C1", "#E57373", "#A94064", "#FFCBA4"],
  },
  {
    id: 53,
    name: "Illuminating Highlighter",
    category: "Face",
    image: "/images/products/highlighter.jpg",
    description: "Luminous highlighter powder that catches light beautifully. Creates a natural-looking glow without glitter or sparkle.",
    shades: ["Champagne", "Rose Gold", "Gold", "Moonlight"],
    colors: ["#F7E98E", "#E8B4A8", "#FFD700", "#E5E4E2"],
  },
  {
    id: 54,
    name: "Luminous Primer",
    category: "Face",
    image: "/images/products/primer.jpg",
    description: "Silky primer that smooths skin and extends makeup wear. Creates a luminous base perfect for all skin types.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 55,
    name: "Cream Contour Palette",
    category: "Face",
    image: "/images/products/contour.jpg",
    description: "Versatile cream contour palette with sculpting shades. Blendable formula for professional contouring results.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#D4A574", "#8B6914", "#654321"],
  },
  {
    id: 56,
    name: "Bronzer Powder",
    category: "Face",
    image: "/images/products/bronzer.jpg",
    description: "Shimmering bronzer powder for sun-kissed glow. Lightweight formula applies smoothly without settling into pores.",
    shades: ["Light Bronze", "Medium Bronze", "Deep Bronze"],
    colors: ["#CDAA7D", "#B8860B", "#8B4513"],
  },
  {
    id: 57,
    name: "Setting Spray",
    category: "Face",
    image: "/images/products/setting-spray.jpg",
    description: "Lightweight setting spray that locks makeup in place. Water-based formula keeps makeup fresh for up to 24 hours.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 58,
    name: "Concealer Pen",
    category: "Face",
    image: "/images/products/concealer.jpg",
    description: "Full-coverage concealer pen with precision applicator. Covers blemishes and dark circles with buildable coverage.",
    shades: ["Porcelain", "Light", "Medium", "Deep"],
    colors: ["#F5E6D3", "#E8D4B8", "#D4A574", "#A67B5B"],
  },
  {
    id: 59,
    name: "Powder Blush",
    category: "Face",
    image: "/images/products/powder-blush.jpg",
    description: "Finely milled powder blush for seamless color. Buildable formula works for subtle or bold application.",
    shades: ["Peach", "Berry", "Plum", "Coral"],
    colors: ["#FFAA88", "#8B4789", "#DDA0DD", "#FF7F50"],
  },
  {
    id: 60,
    name: "Cream Foundation",
    category: "Face",
    image: "/images/products/cream-foundation.jpg",
    description: "Rich cream foundation with moisturizing properties. Provides medium to full coverage with a natural, dewy finish.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#E8D4B8", "#D4A574", "#8B6914"],
  },
  {
    id: 61,
    name: "Hydrating Face Spray",
    category: "Face",
    image: "/images/products/face-spray.jpg",
    description: "Hydrating facial spray with botanical extracts. Refreshes makeup and provides moisture boost throughout the day.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 62,
    name: "Gentle Face Cleanser",
    category: "Face",
    image: "/images/products/face-cleanser.jpg",
    description: "Creamy cleanser that removes makeup and impurities. Leaves skin feeling clean and nourished without stripping.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 63,
    name: "Eye Cream",
    category: "Face",
    image: "/images/products/eye-cream.jpg",
    description: "Lightweight eye cream that targets dark circles and fine lines. Infused with caffeine and peptides for visible results.",
    shades: ["Clear"],
    colors: ["#F5F5DC"],
  },
  {
    id: 64,
    name: "Lip Exfoliator Scrub",
    category: "Face",
    image: "/images/products/lip-exfoliator.jpg",
    description: "Gentle lip scrub with sugar crystals. Removes dead skin for soft, smooth lips perfect for lip color application.",
    shades: ["Natural"],
    colors: ["#E8D4B8"],
  },
  {
    id: 65,
    name: "Matte Finish Powder",
    category: "Face",
    image: "/images/products/face-cleanser.jpg",
    description: "Translucent matte powder that sets makeup without adding color. Controls shine for a flawless matte finish.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 66,
    name: "Liquid Highlighter",
    category: "Face",
    image: "/images/products/highlighter.jpg",
    description: "Liquid highlighter that can be mixed with foundation or worn alone. Creates a dewy, glowing complexion.",
    shades: ["Champagne", "Rose Gold", "Gold"],
    colors: ["#F7E98E", "#E8B4A8", "#FFD700"],
  },
  {
    id: 67,
    name: "BB Cream",
    category: "Face",
    image: "/images/products/foundation.jpg",
    description: "Lightweight BB cream with skincare benefits. Provides light coverage with SPF protection.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#E8D4B8", "#D4A574", "#8B6914"],
  },
  {
    id: 68,
    name: "Blusher Palette",
    category: "Face",
    image: "/images/products/blush.jpg",
    description: "Multi-shade blush palette for creating custom blends. Mix shades to find your perfect flush.",
    shades: ["Light Pink", "Medium Rose", "Deep Berry"],
    colors: ["#FFB6C1", "#E57373", "#A94064"],
  },
  {
    id: 69,
    name: "Correcting Concealer",
    category: "Face",
    image: "/images/products/concealer.jpg",
    description: "Color-correcting concealer for specific concerns. Yellow corrects purple, green conceals redness.",
    shades: ["Green", "Yellow", "Peach"],
    colors: ["#90EE90", "#FFFF00", "#FFCBA4"],
  },
  {
    id: 70,
    name: "Strobing Palette",
    category: "Face",
    image: "/images/products/highlighter.jpg",
    description: "Strobing palette with highlight and contour shades. Create dimensional, sculpted features with ease.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#F7E98E", "#B8860B", "#654321"],
  },
  {
    id: 71,
    name: "Skin Tint SPF",
    category: "Face",
    image: "/images/products/foundation.jpg",
    description: "Sheer skin tint with SPF 30 protection. Lightweight formula enhances natural skin with invisible coverage.",
    shades: ["Fair", "Medium", "Deep"],
    colors: ["#E8D4B8", "#D4A574", "#8B6914"],
  },
  {
    id: 72,
    name: "Blotting Powder",
    category: "Face",
    image: "/images/products/face-cleanser.jpg",
    description: "Absorbent blotting powder controls oil shine. Keeps makeup looking fresh throughout the day.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 73,
    name: "Glow Serum",
    category: "Face",
    image: "/images/products/face-spray.jpg",
    description: "Illuminating serum with light-reflecting particles. Creates a natural, radiant glow from within.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 74,
    name: "Color Corrector Palette",
    category: "Face",
    image: "/images/products/contour.jpg",
    description: "Complete color correction palette for all skin concerns. Includes green, peach, and yellow shades.",
    shades: ["Green", "Peach", "Yellow"],
    colors: ["#90EE90", "#FFCBA4", "#FFFF00"],
  },
  {
    id: 75,
    name: "Finishing Powder",
    category: "Face",
    image: "/images/products/face-cleanser.jpg",
    description: "Ultra-fine finishing powder for a polished look. Mattifies without caking or emphasizing texture.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },

  // SKINCARE - 25 Products
  {
    id: 76,
    name: "Gentle Facial Cleanser",
    category: "Skincare",
    image: "/images/products/face-cleanser.jpg",
    description: "Creamy cleanser formulated for all skin types. Removes makeup and impurities while maintaining skin's natural moisture balance.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 77,
    name: "Hydrating Toner",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Lightweight hydrating toner that balances pH. Contains hyaluronic acid for deep moisture penetration.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 78,
    name: "Vitamin C Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Brightening vitamin C serum for radiant skin. Antioxidant formula reduces dark spots and improves skin texture.",
    shades: ["Golden"],
    colors: ["#FFD700"],
  },
  {
    id: 79,
    name: "Retinol Night Cream",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Nourishing night cream with retinol for cell renewal. Reduces fine lines and improves skin elasticity while you sleep.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 80,
    name: "Hyaluronic Acid Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Hydrating serum with hyaluronic acid molecules. Plumps skin and maintains moisture for 24 hours.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 81,
    name: "Moisturizing Face Cream",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Rich moisturizer with natural oils and butters. Nourishes dry skin without clogging pores.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 82,
    name: "Exfoliating Face Scrub",
    category: "Skincare",
    image: "/images/products/lip-exfoliator.jpg",
    description: "Gentle exfoliating scrub with natural beads. Removes dead skin for brighter, smoother complexion.",
    shades: ["Beige"],
    colors: ["#F5E6D3"],
  },
  {
    id: 83,
    name: "Sunscreen SPF 50",
    category: "Skincare",
    image: "/images/products/face-cleanser.jpg",
    description: "Lightweight sunscreen with SPF 50 protection. Water-resistant formula suitable for all skin types.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 84,
    name: "Nourishing Face Oil",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Luxurious facial oil with essential oils. Provides deep hydration and creates radiant, glowing skin.",
    shades: ["Golden"],
    colors: ["#FFD700"],
  },
  {
    id: 85,
    name: "Pore-Minimizing Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Mattifying serum that visually reduces pore appearance. Creates smooth, poreless-looking skin.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 86,
    name: "Anti-Aging Face Mask",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Hydrating sheet mask with peptides and antioxidants. Improves skin elasticity and reduces fine lines.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 87,
    name: "Brightening Essence",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Lightweight essence that brightens and hydrates. Preps skin for better absorption of serums and creams.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 88,
    name: "Acne-Fighting Spot Treatment",
    category: "Skincare",
    image: "/images/products/face-cleanser.jpg",
    description: "Targeted treatment for blemishes. Contains salicylic acid to clear breakouts quickly.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 89,
    name: "Calming Face Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Soothing serum for sensitive, irritated skin. Reduces redness and inflammation with natural botanicals.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 90,
    name: "Peptide Eye Cream",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Advanced eye cream targeting wrinkles and dark circles. Peptides boost collagen production for firmer skin.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 91,
    name: "Detoxifying Clay Mask",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Purifying clay mask that draws out impurities. Leaves skin feeling refreshed and clarified.",
    shades: ["Green"],
    colors: ["#90EE90"],
  },
  {
    id: 92,
    name: "Hydrating Sheet Mask",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Intensive hydration mask with essence. Perfect for dry, dehydrated skin needing moisture boost.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 93,
    name: "Balancing Facial Tonic",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Alcohol-free tonic that balances oil and hydration. Preps skin for optimal product absorption.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 94,
    name: "Firming Neck Cream",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Specialized cream for delicate neck and décolletage area. Firms and tightens skin.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 95,
    name: "Deep Cleansing Oil",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Dissolves makeup and impurities without stripping. Creates soft, supple skin after cleansing.",
    shades: ["Golden"],
    colors: ["#FFD700"],
  },
  {
    id: 96,
    name: "Mattifying Primer Serum",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Dual-purpose serum that mattifies and primes. Creates perfect base for makeup application.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 97,
    name: "Collagen Boosting Mask",
    category: "Skincare",
    image: "/images/products/eye-cream.jpg",
    description: "Intensive mask stimulating collagen production. Firms and plumps skin for youthful appearance.",
    shades: ["White"],
    colors: ["#FFFFFF"],
  },
  {
    id: 98,
    name: "Illuminating Facial Oil",
    category: "Skincare",
    image: "/images/products/face-spray.jpg",
    description: "Lightweight oil with light-reflecting particles. Creates luminous, glowing complexion.",
    shades: ["Golden"],
    colors: ["#FFD700"],
  },
  {
    id: 99,
    name: "Reparative Lip Mask",
    category: "Skincare",
    image: "/images/products/lip-balm.jpg",
    description: "Intensive treatment mask for lips. Heals and hydrates for soft, plump lips.",
    shades: ["Clear"],
    colors: ["#F5F5DC"],
  },
  {
    id: 100,
    name: "Resurfacing Exfoliant",
    category: "Skincare",
    image: "/images/products/face-cleanser.jpg",
    description: "Chemical exfoliant with AHAs and BHAs. Gently removes dead skin for smooth, radiant complexion.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },

  // EYE SHADOW - 25 Products
  {
    id: 101,
    name: "Prismatic Eyeshadow Palette",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Multidimensional eyeshadow palette with iridescent shades. Creates holographic, color-shifting eye looks.",
    shades: ["Hologram", "Aurora", "Opal", "Prism"],
    colors: ["#F0F8FF", "#E0FFFF", "#F5F5DC", "#FFE4E1"],
  },
  {
    id: 102,
    name: "Velvet Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Smooth velvet eyeshadow with buttery texture. Blends effortlessly for seamless color application.",
    shades: ["Plum", "Rose", "Taupe", "Bronze"],
    colors: ["#4B0082", "#FF1493", "#A9927D", "#CD7F32"],
  },
  {
    id: 103,
    name: "Metallic Eyeshadow Trio",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Three shimmering metallic shades in complementary colors. Creates high-impact metallic eye looks.",
    shades: ["Gold", "Silver", "Copper"],
    colors: ["#FFD700", "#C0C0C0", "#B87333"],
  },
  {
    id: 104,
    name: "Matte Eyeshadow Collection",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Collection of finely-milled matte eyeshadows. Perfect for blending and creating dimension.",
    shades: ["Nude", "Burgundy", "Taupe", "Black"],
    colors: ["#DAA59C", "#800020", "#A9927D", "#2C2C2C"],
  },
  {
    id: 105,
    name: "Watercolor Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Water-activated eyeshadow that transforms with moisture. Create painted watercolor eye designs.",
    shades: ["Ocean", "Forest", "Sunset"],
    colors: ["#0077BE", "#355C3D", "#FF7F50"],
  },
  {
    id: 106,
    name: "Cream Eyeshadow Compact",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Creamy eyeshadow in compact form. Easy to apply with fingers or brush for quick eye looks.",
    shades: ["Champagne", "Copper", "Emerald"],
    colors: ["#F7E98E", "#B87333", "#50C878"],
  },
  {
    id: 107,
    name: "Glitter Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Chunky glitter eyeshadow with adhesive base. Creates bold, sparkly statement eye looks.",
    shades: ["Gold", "Pink", "Purple"],
    colors: ["#FFD700", "#FFC0CB", "#DDA0DD"],
  },
  {
    id: 108,
    name: "Pearl Eyeshadow Powder",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Loose pearl eyeshadow with luminous finish. Mix with primer for intensified color or wear dry.",
    shades: ["White", "Pink", "Gold"],
    colors: ["#FFFFFF", "#FFB6C1", "#FFD700"],
  },
  {
    id: 109,
    name: "Eyeliner & Eyeshadow Duo",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Two-in-one product serves as both eyeliner and eyeshadow. Versatile for multiple eye looks.",
    shades: ["Brown", "Black", "Navy"],
    colors: ["#8B4513", "#000000", "#191970"],
  },
  {
    id: 110,
    name: "Chromatic Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "High-chromatic eyeshadow with intense pigmentation. Creates vivid, multi-dimensional eye color.",
    shades: ["Electric", "Neon", "Vibrant"],
    colors: ["#00FFFF", "#39FF14", "#FF006E"],
  },
  {
    id: 111,
    name: "Satin Eyeshadow Stick",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Satin-finish eyeshadow stick with blendable formula. Easy to apply and smudge for gradient eyes.",
    shades: ["Mauve", "Bronze", "Taupe"],
    colors: ["#9B7BA8", "#CD7F32", "#A9927D"],
  },
  {
    id: 112,
    name: "Duochrome Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Shift-color eyeshadow that changes hue at different angles. Creates stunning color-changing effect.",
    shades: ["Green-Gold", "Purple-Copper", "Blue-Gold"],
    colors: ["#6B8E23", "#9370DB", "#4169E1"],
  },
  {
    id: 113,
    name: "Eyeshadow Converter",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Liquid primer that converts loose eyeshadow to gel. Creates long-lasting, waterproof application.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 114,
    name: "Multi-Use Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Versatile eyeshadow usable on eyes, face, and lips. Creates cohesive makeup look with minimal products.",
    shades: ["Rose", "Berry", "Nude"],
    colors: ["#FF1493", "#8B4789", "#DAA59C"],
  },
  {
    id: 115,
    name: "Wet & Dry Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Eyeshadow usable wet or dry for varied intensity. Perfect for both subtlety and drama.",
    shades: ["Taupe", "Burgundy", "Gold"],
    colors: ["#A9927D", "#800020", "#FFD700"],
  },
  {
    id: 116,
    name: "Sparkle Eyeshadow Dust",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Finely milled sparkle dust for layering. Creates subtle shimmer or bold glitter effect.",
    shades: ["Silver", "Gold", "Copper"],
    colors: ["#C0C0C0", "#FFD700", "#B87333"],
  },
  {
    id: 117,
    name: "Organic Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Natural, chemical-free eyeshadow made with organic ingredients. Gentle formula for sensitive eyes.",
    shades: ["Earth Tone", "Warm Brown", "Soft Gold"],
    colors: ["#8B4513", "#A0522D", "#DAA520"],
  },
  {
    id: 118,
    name: "Gradient Eyeshadow Set",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Set of three gradient shades for easy ombre eyes. Creates professional gradient eyeshadow look.",
    shades: ["Light", "Medium", "Dark"],
    colors: ["#F5E6D3", "#D4A574", "#8B4513"],
  },
  {
    id: 119,
    name: "Pigmented Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Highly pigmented eyeshadow for bold color payoff. Single stroke delivers full, rich color.",
    shades: ["Emerald", "Sapphire", "Amethyst"],
    colors: ["#50C878", "#0F52BA", "#9966CC"],
  },
  {
    id: 120,
    name: "Cooling Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Cooling eyeshadow with menthol for refreshing sensation. Reduces puffiness while adding color.",
    shades: ["Cool Taupe", "Cool Plum"],
    colors: ["#A9927D", "#663399"],
  },
  {
    id: 121,
    name: "Stamping Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Specialized eyeshadow for stamping intricate patterns. Create detailed nail art on eyelids.",
    shades: ["Black", "Blue", "Red"],
    colors: ["#000000", "#0000FF", "#FF0000"],
  },
  {
    id: 122,
    name: "Illuminating Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Light-reflecting eyeshadow that creates luminous glow. Perfect for highlighting inner corner or brow bone.",
    shades: ["Pearl", "Diamond", "Moonstone"],
    colors: ["#F0F8FF", "#E8E8E8", "#F5F5DC"],
  },
  {
    id: 123,
    name: "Thermal Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Temperature-reactive eyeshadow that changes with body heat. Creates unique color-shifting effect.",
    shades: ["Thermal"],
    colors: ["#FF6B6B"],
  },
  {
    id: 124,
    name: "Eyelid Primer & Eyeshadow",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-stick.jpg",
    description: "Combination primer and eyeshadow in one. Preps eyelids while applying color simultaneously.",
    shades: ["Light", "Medium"],
    colors: ["#F5E6D3", "#D4A574"],
  },
  {
    id: 125,
    name: "Sculpting Eyeshadow Palette",
    category: "Eye Shadow",
    image: "/images/products/eyeshadow-palette.jpg",
    description: "Palette with contouring and highlighting shades. Creates sculpted, dimensional eye makeup look.",
    shades: ["Highlight", "Contour", "Shadow"],
    colors: ["#F7E98E", "#8B4513", "#2C2C2C"],
  },

  // HIGHLIGHTER - 25 Products
  {
    id: 126,
    name: "Luminous Glow Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Luminous highlighter with subtle shimmer for natural-looking glow. Flatters all skin tones beautifully.",
    shades: ["Champagne", "Rose Gold", "Gold"],
    colors: ["#F7E98E", "#E8B4A8", "#FFD700"],
  },
  {
    id: 127,
    name: "Liquid Glow Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Liquid highlighter that can be mixed with foundation for all-over glow. Creates dewy, radiant finish.",
    shades: ["Luminous", "Rosy", "Golden"],
    colors: ["#FFE4B5", "#E8B4A8", "#FFD700"],
  },
  {
    id: 128,
    name: "Prismatic Highlight Powder",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Multi-colored prismatic highlighter with iridescent finish. Creates stunning holographic glow effect.",
    shades: ["Rainbow"],
    colors: ["#E0FFFF"],
  },
  {
    id: 129,
    name: "Baked Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Baked highlighter formula for concentrated pigment. Delivers intense glow with minimal product.",
    shades: ["Champagne", "Copper", "Gold"],
    colors: ["#F7E98E", "#B87333", "#FFD700"],
  },
  {
    id: 130,
    name: "Cream Highlight",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Creamy highlighter that blends seamlessly. Perfect for dewy, skin-like luminous finish.",
    shades: ["Pearl", "Rose", "Gold"],
    colors: ["#F0F8FF", "#FFB6C1", "#FFD700"],
  },
  {
    id: 131,
    name: "Holographic Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Holographic highlighter with color-shifting effect. Creates otherworldly, luminous appearance.",
    shades: ["Hologram"],
    colors: ["#F0F8FF"],
  },
  {
    id: 132,
    name: "Strobing Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Ultra-bright strobing highlighter for statement glow. Creates sculpted, lifted appearance.",
    shades: ["Bright", "Extra Bright"],
    colors: ["#FFFFFF", "#FFFACD"],
  },
  {
    id: 133,
    name: "Shimmer Highlight Stick",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Convenient stick highlighter for on-the-go application. Creamy formula glides on smoothly.",
    shades: ["Champagne", "Rose Gold"],
    colors: ["#F7E98E", "#E8B4A8"],
  },
  {
    id: 134,
    name: "Pearlescent Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Pearlescent finish highlighter with soft shimmer. Creates elegant, sophisticated glow.",
    shades: ["Pearl", "Ivory", "Pale Gold"],
    colors: ["#F0F8FF", "#FFFFF0", "#FAFAD2"],
  },
  {
    id: 135,
    name: "Satin Finish Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Smooth satin-finish highlighter for subtle luminosity. Perfect for everyday, natural-looking glow.",
    shades: ["Soft Shimmer", "Warm Glow"],
    colors: ["#E8E8E8", "#FFE4B5"],
  },
  {
    id: 136,
    name: "Matte Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Unique matte highlighter for non-traditional glow. Creates soft, diffused light reflection.",
    shades: ["Milk White", "Soft Peach"],
    colors: ["#FFFACD", "#FFCBA4"],
  },
  {
    id: 137,
    name: "Chromatic Highlight Powder",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "High-chromatic highlighting powder with vibrant shimmer. Creates bold, saturated glow effect.",
    shades: ["Electric Gold", "Neon Pink"],
    colors: ["#FFD700", "#FF1493"],
  },
  {
    id: 138,
    name: "Dual-Tone Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Two complementary highlight shades swirled together. Creates dimensional, blended glow.",
    shades: ["Rose-Gold", "Gold-Peach"],
    colors: ["#E8B4A8", "#FFD700"],
  },
  {
    id: 139,
    name: "Sculpting Highlight",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Contoured highlight powder for sculpted features. Creates dimensional, lifted face appearance.",
    shades: ["Light", "Medium"],
    colors: ["#FFFACD", "#FFD700"],
  },
  {
    id: 140,
    name: "Monochromatic Highlighter Set",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Set of three highlighting shades in same color family. Creates gradient, customizable glow.",
    shades: ["Light", "Medium", "Deep"],
    colors: ["#FFFACD", "#FFD700", "#DAA520"],
  },
  {
    id: 141,
    name: "Wet & Dry Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Versatile highlighter usable wet for liquid glow or dry for powder shimmer.",
    shades: ["Gold", "Rose"],
    colors: ["#FFD700", "#FF69B4"],
  },
  {
    id: 142,
    name: "Cooling Highlight",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Cooling formula highlighter with menthol. Refreshes while providing luminous glow.",
    shades: ["Cool Gold", "Cool Rose"],
    colors: ["#DAA520", "#DB7093"],
  },
  {
    id: 143,
    name: "Metallic Liquid Highlight",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Metallic liquid highlighter with rich pigmentation. Creates reflective, luminous skin effect.",
    shades: ["Liquid Gold", "Liquid Rose"],
    colors: ["#FFD700", "#FF69B4"],
  },
  {
    id: 144,
    name: "Glitter Highlight",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Glitter-infused highlighting powder for sparkly glow. Creates bold, eye-catching highlight.",
    shades: ["Gold Glitter", "Pink Glitter"],
    colors: ["#FFD700", "#FFB6C1"],
  },
  {
    id: 145,
    name: "Strobing Stick Highlight",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Ultra-bright highlight stick for strobing technique. Easy application with precision tip.",
    shades: ["Bright"],
    colors: ["#FFFFFF"],
  },
  {
    id: 146,
    name: "Loose Highlight Powder",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Finely milled loose highlight powder for customizable intensity. Build coverage gradually.",
    shades: ["Gold", "Rose Gold"],
    colors: ["#FFD700", "#E8B4A8"],
  },
  {
    id: 147,
    name: "Natural Glow Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Natural-looking highlighter for subtle, skin-like glow. Perfect for everyday wear.",
    shades: ["Natural"],
    colors: ["#FFE4B5"],
  },
  {
    id: 148,
    name: "Rainbow Highlight Palette",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Multi-color highlight palette with all skin tone shades. Mix and match for personalized glow.",
    shades: ["Light", "Medium", "Deep"],
    colors: ["#FFFACD", "#FFD700", "#DAA520"],
  },
  {
    id: 149,
    name: "Opulent Glow Highlighter",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Luxurious, opulent highlighter with rich luminosity. Creates lavish, high-end glow effect.",
    shades: ["Opulent Gold", "Opulent Rose"],
    colors: ["#FFD700", "#FFB6C1"],
  },
  {
    id: 150,
    name: "Feathering Highlight Brush",
    category: "Highlighter",
    image: "/images/products/highlighter.jpg",
    description: "Highlight powder with integrated feathering brush. Creates soft, blended highlight application.",
    shades: ["Gold"],
    colors: ["#FFD700"],
  },

  // PRIMER - 25 Products
  {
    id: 151,
    name: "Luminous Face Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Silky primer with light-reflecting particles for luminous finish. Creates smooth base for makeup application.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 152,
    name: "Pore-Minimizing Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Mattifying primer that minimizes pore appearance. Creates poreless-looking base for makeup.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 153,
    name: "Hydrating Primer Gel",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Lightweight hydrating gel primer for dewy finish. Contains hyaluronic acid for moisture.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 154,
    name: "Color-Correcting Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Color-correcting primer in multiple shades. Neutralizes redness, sallowness, or dark spots.",
    shades: ["Green", "Yellow", "Pink"],
    colors: ["#90EE90", "#FFFF00", "#FFB6C1"],
  },
  {
    id: 155,
    name: "Silicone-Free Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Lightweight silicone-free primer for sensitive skin. Natural formula extends makeup wear.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 156,
    name: "Mattifying Primer Powder",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Loose powder primer that mattifies and extends wear. Buildable coverage for different skin needs.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 157,
    name: "Golden Glow Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Subtle warm-toned primer for golden glow base. Creates radiant, sun-kissed appearance.",
    shades: ["Golden"],
    colors: ["#FFD700"],
  },
  {
    id: 158,
    name: "Oil-Control Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Specialized primer for oily skin types. Controls sebum production while keeping makeup fresh.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 159,
    name: "Smoothing Silicone Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Silicone-based primer that fills pores and smooths texture. Creates perfectly smooth base.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 160,
    name: "Strobe Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Luminous strobing primer for highlighted features. Adds instant glow to high points of face.",
    shades: ["Light"],
    colors: ["#FFFACD"],
  },
  {
    id: 161,
    name: "Cooling Primer Gel",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Cooling gel primer for refreshing feel. Calms skin while creating makeup base.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 162,
    name: "Anti-Aging Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Peptide-enriched primer that smooths fine lines. Creates youthful, lifted base for makeup.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 163,
    name: "Brightening Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Brightening primer with vitamin C for radiant glow. Creates illuminated makeup base.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 164,
    name: "Petal Soft Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Velvety soft primer with petal-smooth texture. Creates perfectly refined base for makeup.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 165,
    name: "Balancing Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Balancing primer for combination skin. Controls oil in T-zone while hydrating cheeks.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 166,
    name: "Vitamin Infused Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Primer infused with vitamins A, C, E for skin benefits. Nourishes while priming.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 167,
    name: "Flexible Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Flexible primer that moves with facial expressions. Creates comfortable, natural-looking base.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 168,
    name: "Skin-Tint Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Light-coverage primer that evens skin tone. Creates base that needs minimal foundation.",
    shades: ["Fair", "Medium", "Deep"],
    colors: ["#E8D4B8", "#D4A574", "#8B6914"],
  },
  {
    id: 169,
    name: "Hydro-Gel Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Water-based hydro gel primer for refreshing hydration. Creates plump, dewy skin base.",
    shades: ["Clear"],
    colors: ["#F5F5F5"],
  },
  {
    id: 170,
    name: "Sensitive Skin Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Hypoallergenic primer for sensitive skin. Calming formula preps skin safely.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 171,
    name: "Lightweight Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Ultra-lightweight primer that doesn't feel heavy. Creates invisible base for all makeup types.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 172,
    name: "Film-Forming Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Film-forming primer that extends makeup wear. Creates durable base resistant to fading.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 173,
    name: "Rose-Infused Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Rose-extract primer with soothing properties. Creates calmed, radiant makeup base.",
    shades: ["Rose"],
    colors: ["#FFB6C1"],
  },
  {
    id: 174,
    name: "Multitasking Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "Versatile primer that primes, hydrates, and protects. All-in-one base product.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
  {
    id: 175,
    name: "Performance Primer",
    category: "Primer",
    image: "/images/products/primer.jpg",
    description: "High-performance primer for 24-hour wear. Ensures makeup stays flawless all day.",
    shades: ["Universal"],
    colors: ["#F5F5F5"],
  },
]

const uniqueProducts = Array.from(
  new Map(products.map(item => [item.image, item])).values()
);

export default uniqueProducts;
// export default products;